### ISSUE TITLE
Error: spawn etc\\dist\7zip-lite\7z.exe ENOENT

### ISSUE THREAD

**Issue by MichaelGatesDev** [Robinfr/electron-react-typescript#11]
This boilerplate is really nice and works well but I get this error on starting. Any idea how to fix it?

```
{ Error: spawn D:\Dev\Programs\manny-the-mod-man\dist\7zip-lite\7z.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall:
   'spawn D:\\Dev\\Programs\\manny-the-mod-man\\dist\\7zip-lite\\7z.exe',
  path:
   'D:\\Dev\\Programs\\manny-the-mod-man\\dist\\7zip-lite\\7z.exe',
  spawnargs:
   [ 'x',
     'C:\\Users\\sparta\\AppData\\Roaming\\Electron\\extensions\\fmkadmapgofadopljbjfkapdkoienihi.crx',
     '-y',
     '-oC:\\Users\\sparta\\AppData\\Roaming\\Electron\\extensions\\fmkadmapgofadopljbjfkapdkoienihi' ] }
```

**Comment by psongit** [comment]
Setting 

> node: { __dirname: true }

on the _webpack.base.config.js_ file should solve the issue

Refer [https://webpack.js.org/configuration/node/#node__dirname](url)

**Comment by Robinfr** [comment]
I'm assuming you've solved the problem by now. Let me know if you're still having issues.
