### ISSUE TITLE
Error: spawn hdiutil ENOENT when building Mac version

### ISSUE THREAD

**Issue by freelife2010** [Robinfr/electron-react-typescript#15]
npm run dist -- -mwl
Error: spawn hdiutil ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at _createStageDmg (/home/.../dmg-builder/out/dmg.js:363:26)
    at createStageDmg (/home/.../node_modules/dmg-builder/out/dmg.js:351:26)
    at /home/.../node_modules/dmg-builder/src/dmg.ts:35:27
    at Generator.next (<anonymous>
...

**Comment by Robinfr** [comment]
See https://github.com/electron-userland/electron-builder/issues/811
