### ISSUE TITLE
Can't run debugging on VSCode

### ISSUE THREAD

**Issue by KennyDizi** [Robinfr/electron-react-typescript#29]
clone the repository, install all npm packages and run debug with VSCode but received error:
Debugger listening on ws://127.0.0.1:5355/13148d06-242e-470e-9f38-a1eedfa27bde
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
TypeError: Cannot read property 'on' of undefined
    at Module../src/main/main.ts (e:\electron-react-typescript\src\main\main.ts:49:5)
    at __webpack_require__ (e:\electron-react-typescript\dist\main.js:20:30)
    at e:\electron-react-typescript\dist\main.js:84:18
    at Object.<anonymous> (e:\electron-react-typescript\dist\main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1155:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by Robinfr** [comment]
The `launch.json` is this repo is just an example, so yes just pressing debug won't work. Either use the terminal and use `npm start`, or create a proper `launch.json`.
