### ISSUE TITLE
Compilation error css-loader : Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by BoobaFetes** [Robinfr/electron-react-typescript#8]
Hi Robin,

First thank you for your project.

I has downloaded your project then use the commands : npm install then npm run start-dev

I have the follonwing error while compilling :
`ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/components/Counter.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\SilverStarPort2\source\repos\Teepa research\ReactTS_Electron_WebSite\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadLoader (C:\Users\SilverStarPort2\source\repos\Teepa research\ReactTS_Electron_WebSite\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\SilverStarPort2\source\repos\Teepa research\ReactTS_Electron_WebSite\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\SilverStarPort2\source\repos\Teepa research\ReactTS_Electron_WebSite\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\SilverStarPort2\source\repos\Teepa research\ReactTS_Electron_WebSite\node_modules\loader-runner\lib\LoaderRunner.js:173:18
 @ ./src/components/Counter.scss 4:14-125 18:2-22:4 19:20-131
 @ ./src/components/Counter.tsx
 @ ./src/containers/CounterContainer.ts
 @ ./src/components/Application.tsx
 @ ./src/app.tsx
 @ multi (webpack)-dev-server/client?http://localhost:2003 webpack/hot/dev-server react-hot-loader/patch ./src/app.tsx`

Can you do something for a newbie like me ? 
Your magic debugging spell will be appreciated !

**Comment by BoobaFetes** [comment]
I'm working on Windows 10, VSCode.

**Comment by Robinfr** [comment]
Hi @BoobaFetes, have you managed to resolve the issue in the end? I've just done a massive update to the project. However, your problem seems to be more related to the fact that `node-sass` failed to install. Do you get any error messages/warnings during `npm install`?
